name: Documentation

on:
  # So we can trigger manually if needed
  workflow_dispatch:
  # To confirm any changes to docs build successfully, without deploying them
  pull_request:
  # Pushes to branches do the full build + deployment
  push:
    branches:
      - main
      - "release-*"
    paths:
      - "cmd/**"
      - "docs/**"
      - "pkg/**"
      - ".github/workflows/docs-gen-and-push.yaml"

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}

jobs:
  generate-and-push:
    name: Generate and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # tag=v5.0.0

      - run: git fetch origin gh-pages
      - run: git fetch origin '+refs/tags/v*:refs/tags/v*' --no-tags

      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # tag=v6.0.0
        with:
          go-version: v1.24.5
          cache: true

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c #tag=v6.0.0
        with:
          python-version: '3.10'
          cache: 'pip'

      # mike does not support giving CLI flags for mkdocs, but we also do not
      # want to permanently enable strict mode, so here we enable it just for this
      # task
      - run: |
          echo "strict: true" >> docs/mkdocs.yml

      - run: make generate-cli-docs generate-api-docs deploy-docs
