name: goreleaser

on:
  pull_request:
    paths:
    - .github/workflows/goreleaser.yml
    - .goreleaser.yaml
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # tag=v5.0.0
      with:
        fetch-depth: 0

    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # tag=v5.5.0
      with:
        go-version: v1.24.5

    - name: Download go modules
      run: |
        echo "Downloading modules for go.mod"
        go mod download
        for gomod in **/go.mod; do
          echo "Downloading modules for $gomod"
          cd $(dirname $gomod)
          go mod download
          cd -
        done

    - name: Delete non-semver tags
      run: 'git tag -d $(git tag -l | grep -v "^v")'

    - name: Set LDFLAGS
      run: echo LDFLAGS="$(make ldflags)" >> $GITHUB_ENV

    - name: Run GoReleaser on tag
      if: github.event_name != 'pull_request'
      uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # tag=v6.4.0
      with:
        distribution: goreleaser
        version: latest
        args: release --timeout 60m --parallelism 1 --fail-fast
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        KREW_GITHUB_TOKEN: ${{ secrets.KREW_GITHUB_TOKEN }}

    - name: Run GoReleaser on pull request
      if: github.event_name == 'pull_request'
      uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # tag=v6.4.0
      with:
        distribution: goreleaser
        version: latest
        args: release --timeout 60m --snapshot --parallelism 1 --fail-fast
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        KREW_GITHUB_TOKEN: ${{ secrets.KREW_GITHUB_TOKEN }}

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # tag=v4.6.2
      if: ${{ always() }}
      with:
        name: binaries
        path: dist/*.tar.gz
